export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';

export const CREATE_TODO = 'CREATE_TODO';
export const FETCH_TODO = 'FETCH_TODO';
export const FETCH_TODOS = 'FETCH_TODOS';
export const DELETE_TODO = 'DELETE_TODOS';
export const EDIT_TODO = 'EDIT_TODO';

export const CREATE_PRODUCT = 'CREATE_PRODUCT';
export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const DELETE_PRODUCT = 'DELETE_PRODUCT';
export const EDIT_PRODUCT = 'EDIT_PRODUCT';

export const ADD_TO_SHOPPING_LIST = 'ADD_TO_SHOPPING_LIST';
export const FETCH_SHOPPING_LIST_PRODUCTS = 'FETCH_SHOPPING_LIST_PRODUCTS';
export const EDIT_SHOPPING_LIST_PRODUCT = 'EDIT_SHOPPING_LIST_PRODUCT';
export const FETCH_SHOPPING_LIST_PRODUCT = 'FETCH_SHOPPING_LIST_PRODUCT';
export const INCREMENT_SHOPPING_LIST_PRODUCT = 'INCREMENT_SHOPPING_LIST_PRODUCT';