export const SIGN_IN = 'SIGN_IN';
export const SIGN_OUT = 'SIGN_OUT';

export const CREATE_RECIPE = 'CREATE_RECIPE';
export const FETCH_RECIPE = 'FETCH_RECIPE';
export const FETCH_RECIPES = 'FETCH_RECIPES';
export const DELETE_RECIPE = 'DELETE_RECIPE';
export const EDIT_RECIPE = 'EDIT_RECIPE';

export const CREATE_TODO = 'CREATE_TODO';
export const FETCH_TODO = 'FETCH_TODO';
export const FETCH_TODOS = 'FETCH_TODOS';
export const DELETE_TODO = 'DELETE_TODOS';
export const EDIT_TODO = 'EDIT_TODO';

export const CREATE_GROCERIES = 'CREATE_GROCERIES';
export const FETCH_GROCERIES = 'FETCH_GROCERIES';
export const FETCH_ALL_GROCERIES = 'FETCH_ALL_GROCERIES';
export const DELETE_GROCERIES = 'DELETE_GROCERIES';
export const EDIT_GROCERIES = 'EDIT_GROCERIES';